export {
	type ClickOptions,
	type ClickResult,
	type ConsoleLogsOptions,
	DesktopAutomation,
	type DomElement,
	type NavigateOptions,
	type ScreenshotRect,
	type ScreenshotResult,
	type SendKeysOptions,
	type TypeTextOptions,
	type WaitForOptions,
	type WaitForResult,
	type WindowInfo,
} from "./desktop-automation.js";
export {
	type BlankFrameResult,
	type BlankFrameSample,
	type BoundsSnapshot,
	buildVisualStabilityFailures,
	classifyBlankFramePixels,
	classifyDomChurn,
	classifyLayoutSelector,
	classifyPersistentSelector,
	DEFAULT_VISUAL_STABILITY_THRESHOLDS,
	type DecodedPngImage,
	type DomChurnResult,
	decodePngToRgba,
	formatVisualStabilityReport,
	type LayoutSample,
	type LayoutSelectorResult,
	normalizeVisualStabilityThresholds,
	type PersistentRemoval,
	type PersistentSelectorResult,
	type VisualStabilityAction,
	type VisualStabilityArtifactOptions,
	type VisualStabilityArtifacts,
	type VisualStabilityFailure,
	type VisualStabilityOptions,
	type VisualStabilityReport,
	type VisualStabilityThresholdInput,
	type VisualStabilityThresholds,
} from "./visual-stability.js";
